#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

PROG=/usr/sbin/re-cs-07-monitor

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger re_cs_07
}
